from flask import Flask, jsonify, request
import json

app = Flask(__name__)

# Mock permit data (replace with actual database interaction later)
with open('permits.json', 'r') as f:
    permits_data = json.load(f)

@app.route('/detect_permits', methods=['GET'])
def detect_permits():
    return jsonify(permits_data)

@app.route('/generate_letter', methods=['POST'])
def generate_letter():
    data = request.get_json()
    permit_id = data.get('permit_id')
    user_name = data.get('user_name')
    user_email = data.get('user_email')

    # In a real scenario, you would use the Gemini API here to generate the letter
    # based on permit_id and other details.
    # For now, we return a placeholder.

    # Mock AI response
    mock_letter_content = f"""
Subject: Objection to Factory Farm Permit Application (Permit ID: {permit_id})

Dear Sir/Madam,

This letter serves as a formal objection to the proposed factory farm permit application with Permit ID: {permit_id}.

We are deeply concerned about the potential environmental impact, animal welfare issues, and public health risks associated with such an operation.

[Further detailed arguments citing Indian regulations would go here, generated by AI]

Sincerely,
{user_name}
{user_email}
"""

    # Mock email alert (print to console for now)
    print(f"""
--- MOCK EMAIL ALERT ---
To: {user_email}
Subject: 🚨 New Factory Farm Permit Filed in [Location] (Permit ID: {permit_id})

Dear {user_name},

A new factory farm permit application (Permit ID: {permit_id}) has been filed.
You can download your objection letter here: [Link to download - conceptual for now]

--- END MOCK EMAIL ALERT ---
""")

    return jsonify({'letter_content': mock_letter_content})

if __name__ == '__main__':
    app.run(debug=True)
