// Email templates for different scenarios

const emailTemplates = {
  objectionSubmission: {
    subject: (projectTitle) => `Objection to Factory Farm Permit: ${projectTitle}`,
    html: (objectionLetter, submitterInfo, permitDetails) => `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { background-color: #f4f4f4; padding: 20px; text-align: center; }
            .content { padding: 20px; }
            .footer { background-color: #f4f4f4; padding: 10px; text-align: center; font-size: 0.9em; }
            .letter { background-color: #f9f9f9; padding: 15px; border-left: 4px solid #007acc; margin: 15px 0; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>Factory Farm Objection Submission</h2>
            <p>From: ${submitterInfo.name} (${submitterInfo.email})</p>
          </div>
          
          <div class="content">
            <h3>Permit Details:</h3>
            <p><strong>Project:</strong> ${permitDetails.project_title}</p>
            <p><strong>Location:</strong> ${permitDetails.location}</p>
            <p><strong>Activity:</strong> ${permitDetails.activity}</p>
            <p><strong>Capacity:</strong> ${permitDetails.capacity}</p>
            
            <h3>Objection Letter:</h3>
            <div class="letter">
              <pre style="white-space: pre-wrap; font-family: Arial, sans-serif;">${objectionLetter}</pre>
            </div>
            
            <h3>Submitter Information:</h3>
            <p><strong>Name:</strong> ${submitterInfo.name}</p>
            <p><strong>Address:</strong> ${submitterInfo.address}, ${submitterInfo.city}, ${submitterInfo.postalCode}</p>
            <p><strong>Phone:</strong> ${submitterInfo.phone}</p>
            <p><strong>Email:</strong> ${submitterInfo.email}</p>
          </div>
          
          <div class="footer">
            <p>This email was automatically generated by the Automated Factory Farm Objection Generator</p>
          </div>
        </body>
      </html>
    `
  },
  
  submissionConfirmation: {
    subject: (projectTitle) => `Confirmation: Objection Submitted for ${projectTitle}`,
    html: (objectionLetter, submitterInfo, permitDetails) => `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { background-color: #d4edda; padding: 20px; text-align: center; color: #155724; }
            .content { padding: 20px; }
            .footer { background-color: #f8f9fa; padding: 10px; text-align: center; font-size: 0.9em; }
            .letter { background-color: #f9f9f9; padding: 15px; border-left: 4px solid #28a745; margin: 15px 0; }
          </style>
        </head>
        <body>
          <div class="header">
            <h2>Objection Submission Confirmation</h2>
            <p>Successfully submitted to the relevant authorities</p>
          </div>
          
          <div class="content">
            <p>Dear ${submitterInfo.name},</p>
            
            <p>Your objection to the factory farm permit has been successfully submitted. Here are the details:</p>
            
            <h3>Permit Details:</h3>
            <p><strong>Project:</strong> ${permitDetails.project_title}</p>
            <p><strong>Location:</strong> ${permitDetails.location}</p>
            <p><strong>Activity:</strong> ${permitDetails.activity}</p>
            
            <h3>Your Objection Letter:</h3>
            <div class="letter">
              <pre style="white-space: pre-wrap; font-family: Arial, sans-serif;">${objectionLetter}</pre>
            </div>
            
            <p>The relevant authorities have been notified of your objection. You can reference this submission with your email address if you need to follow up.</p>
          </div>
          
          <div class="footer">
            <p>Thank you for using the Automated Factory Farm Objection Generator</p>
          </div>
        </body>
      </html>
    `
  },
  
 statusUpdate: {
    subject: (projectTitle, status) => `Status Update: ${projectTitle} - ${status}`,
    html: (submissionId, status, notes, permitDetails) => `
      <html>
        <head>
          <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .header { padding: 20px; text-align: center; }
            .status-pending { background-color: #fff3cd; color: #856404; }
            .status-approved { background-color: #f8d7da; color: #721c24; }
            .status-rejected { background-color: #d4edda; color: #155724; }
            .status-under-review { background-color: #cce5ff; color: #004085; }
            .content { padding: 20px; }
            .footer { background-color: #f8f9fa; padding: 10px; text-align: center; font-size: 0.9em; }
          </style>
        </head>
        <body>
          <div class="header status-${status.toLowerCase().replace(' ', '-')}">
            <h2>Permit Status Update</h2>
            <p>Submission ID: ${submissionId}</p>
          </div>
          
          <div class="content">
            <h3>Permit Details:</h3>
            <p><strong>Project:</strong> ${permitDetails.project_title}</p>
            <p><strong>Location:</strong> ${permitDetails.location}</p>
            
            <h3>Status Update:</h3>
            <p><strong>New Status:</strong> ${status}</p>
            ${notes ? `<p><strong>Notes:</strong> ${notes}</p>` : ''}
            
            <p>Please check the relevant authority's website for more information about this permit application.</p>
          </div>
          
          <div class="footer">
            <p>You received this email because you submitted an objection to this permit. You can update your notification preferences in your account settings.</p>
          </div>
        </body>
      </html>
    `
  }
};

module.exports = emailTemplates;