const puppeteer = require('puppeteer');

// Function to generate a PDF from objection letter content
async function generateObjectionLetterPDF(objectionLetter, permitDetails, submitterInfo) {
  // Validate inputs
  if (!objectionLetter || typeof objectionLetter !== 'string') {
    throw new Error('Invalid objection letter provided');
  }
  
  if (!permitDetails || typeof permitDetails !== 'object') {
    throw new Error('Invalid permit details provided');
  }
  
  if (!submitterInfo || typeof submitterInfo !== 'object') {
    throw new Error('Invalid submitter information provided');
  }
  
  // Validate required fields in permit details
  if (!permitDetails.project_title) {
    throw new Error('Project title is required in permit details');
  }
  
  // Validate required fields in submitter info
  if (!submitterInfo.name || !submitterInfo.address || !submitterInfo.city ||
      !submitterInfo.postalCode || !submitterInfo.phone || !submitterInfo.email) {
    throw new Error('Missing required submitter information fields');
  }
  
  let browser;
  try {
    browser = await puppeteer.launch({
      headless: true, // Set to false for debugging
      args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    
    const page = await browser.newPage();
    
    // Create HTML content for the PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Factory Farm Objection Letter</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            text-align: center;
            border-bottom: 2px solid #007acc;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .permit-details {
            background-color: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
          }
          .submitter-info {
            background-color: #f0f8ff;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
          }
          .letter-content {
            white-space: pre-wrap;
            line-height: 1.8;
          }
          .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #ccc;
            text-align: center;
            font-size: 0.8em;
            color: #666;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Objection Letter to Factory Farm Permit</h1>
          <p>Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        
        <div class="permit-details">
          <h3>Permit Details</h3>
          <p><strong>Project Title:</strong> ${permitDetails.project_title || 'N/A'}</p>
          <p><strong>Location:</strong> ${permitDetails.location || 'N/A'}</p>
          <p><strong>Activity:</strong> ${permitDetails.activity || 'N/A'}</p>
          <p><strong>Capacity:</strong> ${permitDetails.capacity || 'N/A'}</p>
        </div>
        
        <div class="submitter-info">
          <h3>Submitted By</h3>
          <p><strong>Name:</strong> ${submitterInfo.name || 'N/A'}</p>
          <p><strong>Address:</strong> ${submitterInfo.address || 'N/A'}, ${submitterInfo.city || 'N/A'}, ${submitterInfo.postalCode || 'N/A'}</p>
          <p><strong>Contact:</strong> ${submitterInfo.phone || 'N/A'} | ${submitterInfo.email || 'N/A'}</p>
          <p><strong>Date:</strong> ${submitterInfo.date || new Date().toISOString().split('T')[0]}</p>
        </div>
        
        <div class="letter-content">
          <h3>Objection Letter</h3>
          <pre style="font-family: Arial, sans-serif; white-space: pre-wrap;">${objectionLetter}</pre>
        </div>
        
        <div class="footer">
          <p>This document was automatically generated by the Automated Factory Farm Objection Generator</p>
          <p>Reference: ${permitDetails.project_title || 'unknown'} | ID: ${Date.now()}</p>
        </div>
      </body>
      </html>
    `;
    
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    const pdfBuffer = await page.pdf({
      format: 'A4',
      margin: {
        top: '20px',
        right: '20px',
        bottom: '20px',
        left: '20px'
      }
    });
    
    return pdfBuffer;
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF: ' + error.message);
  } finally {
    if (browser) {
      await browser.close();
    }
  }
}

module.exports = { generateObjectionLetterPDF };