// Lightweight letter formatter — NO puppeteer, NO Chromium, NO memory hog
// Generates a clean HTML string that can be printed to PDF via browser's Print dialog

function generateLetterHTML(objectionLetter, permitDetails, submitterInfo) {
    if (!objectionLetter || typeof objectionLetter !== 'string') {
        throw new Error('Invalid objection letter provided');
    }

    const escapeHTML = (str) =>
        String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

    return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Objection Letter — ${escapeHTML(permitDetails?.project_title || 'Factory Farm')}</title>
<style>
  @media print { body { margin: 0; } .no-print { display: none; } }
  body { font-family: Georgia, 'Times New Roman', serif; line-height: 1.7; color: #1a1a1a; max-width: 700px; margin: 40px auto; padding: 20px; }
  .header { text-align: center; border-bottom: 2px solid #1a5632; padding-bottom: 16px; margin-bottom: 24px; }
  .header h1 { font-size: 18px; margin: 0 0 4px; }
  .header p { font-size: 12px; color: #666; margin: 0; }
  .meta { background: #f5f5f5; padding: 12px 16px; border-radius: 4px; margin-bottom: 20px; font-size: 13px; }
  .meta strong { display: inline-block; min-width: 100px; }
  .letter { white-space: pre-wrap; font-size: 14px; }
  .footer { margin-top: 32px; padding-top: 12px; border-top: 1px solid #ddd; text-align: center; font-size: 11px; color: #999; }
  .no-print { text-align: center; margin-bottom: 20px; }
  .no-print button { background: #1a5632; color: white; border: none; padding: 10px 24px; border-radius: 6px; font-size: 14px; cursor: pointer; }
</style>
</head>
<body>
<div class="no-print"><button onclick="window.print()">Print / Save as PDF</button></div>
<div class="header">
  <h1>FORMAL OBJECTION LETTER</h1>
  <p>${escapeHTML(permitDetails?.project_title || '')} — ${escapeHTML(permitDetails?.location || '')}</p>
</div>
<div class="meta">
  <strong>Project:</strong> ${escapeHTML(permitDetails?.project_title || 'N/A')}<br>
  <strong>Location:</strong> ${escapeHTML(permitDetails?.location || 'N/A')}<br>
  <strong>Activity:</strong> ${escapeHTML(permitDetails?.activity || 'N/A')}<br>
  <strong>Date:</strong> ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
</div>
<div class="letter">${escapeHTML(objectionLetter)}</div>
<div class="footer">
  Generated by AFFOG — Automated Factory Farm Objection Generator<br>
  Reference: ${escapeHTML(permitDetails?.project_title || 'unknown')} | ${new Date().toISOString().split('T')[0]}
</div>
</body>
</html>`;
}

module.exports = { generateLetterHTML };
